### ISSUE TITLE
command execute wrong

### ISSUE THREAD

**Issue by bugmeout** [GOVCERT-LU/ce1sus#2]
[Install Guide--1.6 uwsgi] (https://github.com/GOVCERT-LU/ce1sus/blob/0.11.X/docs/DOCUMENTATION.md#16-uwsgi) using a command

        cp scripts/install/uwsgi/ce1sus.ini_tmpl config/ce1sus.conf /etc/uwsgi/apps-available/ce1sus.ini

is this right?

      laber@ubuntu:~/ce1sus$ cp scripts/install/uwsgi/ce1sus.ini_tmpl config/ce1sus.conf /etc/uwsgi/apps-available/ce1sus.ini
      cp: target /etc/uwsgi/apps-available/ce1sus.ini is not a directory

i use commands as:
   
        apt-get install uwsgi uwgsi-plugin-python
        cp scripts/install/uwsgi/ce1sus.ini_tmpl  /etc/uwsgi/apps-available/ce1sus.ini
        ln -s /etc/uwsgi/apps-available/ce1sus.ini /etc/uwsgi/apps-enabled/

then
      modify the file  ce1sus.ini -->  pythonpath =/home/laber/cel1sus

finally
        /etc/init.d/uwsgi restart

but the services can't start.

**Comment by jhemp** [comment]
Hello,

You are right the command is incorrect it should be 

cp scripts/install/uwsgi/ce1sus.ini_tmpl /etc/uwsgi/apps-available/ce1sus.ini

The "config/ce1sus.conf" is too much

Therefore the command did nothing at all, by using the one above it will work

Thanks for reporting this

**Comment by jhemp** [comment]
and not to forget edit the line

pythonpath = /path/to/ce1sus

to the correct destination

**Comment by bugmeout** [comment]
@jhemp  thanks for your attention.  my pythonpath had set to `/home/username/ce1sus/` before.
 
the project trees like this: .
```
laber@ubuntu:~/ce1sus$ tree -L 1
.
├── ce1sus
├── ce1sus-run.py
├── CHANGELOG
├── config
├── cybox -> libs/python-cybox/cybox
├── docs
├── eml_parser -> libs/eml_parser/eml_parser/
├── htdocs
├── ioc_observable.py -> libs/openioc-to-stix/ioc_observable.py
├── ioc_observable.pyc
......
├── libs
├── log
├── magic.py -> libs/python-mag
```

```
laber@ubuntu:/etc/uwsgi/apps-available$ vim ce1sus.ini

[uwsgi]
uid = www-data
gid = www-data
pythonpath = /home/laber/ce1sus
plugins = python27
module = ce1sus-run
workers = 2
vacuum = True

```

but  can't start it as before.
```
laber@ubuntu:/etc/uwsgi/apps-available$ service uwsgi start
 * Starting app server(s) uwsgi                                                         [fail]
laber@ubuntu:/etc/uwsgi/apps-available$ service uwsgi status
 * which one?

```

`python ce1sus-run.py` works fine, and nginx server can visit default `welcome to nginx` page。

**Comment by jhemp** [comment]
did you use the command:

ln -s /etc/uwsgi/apps-available/ce1sus.ini /etc/uwsgi/apps-enabled/

? if there is no link or file in apps-enabled the uswgi won't load it up

**Comment by jhemp** [comment]
Havent seen the [fail] 

in ce1sus.ini stands:
uid = www-data
gid = www-data

this means the uswgi will use www-data:www-data as user:group, this can be that uwsgi can there fore not access the files, my best guess is to look in the logs of uswgi for more informations.

**Comment by bugmeout** [comment]
there is something wrong with my module uwsgi .maybe this one caused this problem .i wil give a feedback when fix this module problem. thanks for you patience and support.

**Comment by jhemp** [comment]
you're welcome

**Comment by bugmeout** [comment]
@jhemp  today i reinstall uwsgi, problem still exists. i checked the log file as you guide,find the problem was casued by configuration file.
log file shows `Listen queue size is greater than the system max net.core.somaxconn (128)` .
 While  template `ce1sus.ini_tmpl` set this size  more than 128
```
***@***:~/ce1sus/scripts/install/uwsgi$ cat ce1sus.ini_tmpl
[uwsgi]
uid = www-data
gid = www-data
pythonpath = /path/to/ce1sus
plugins = python27
module = ce1sus-run
workers = 2
vacuum = True
max-requests = 1000000
harakiri = 120
harakiri-verbose = true
need-app = true
buffer-size = 32768
listen = 200                                  <-- here

```

so i modify the field ,problem solved.

**Comment by jhemp** [comment]
Thanks for this information, I will take a look at it.

**Comment by jhemp** [comment]
Now I see

The config was written for debian whezzy where the limit was higher than in jessie, will change the config to 128. Will change this to prevent future troubles.
